CREATE TABLE `USER_TRANS_INFO` (
	`TRANS_INFO_ID` INT PRIMARY KEY AUTO_INCREMENT,
	`USER_ID` INT NOT NULL,
	`TRANS_DT` TIMESTAMP NOT NULL
);


CREATE TABLE `USER_TRANS_AMT` (
	`TRANS_AMT_ID` INT PRIMARY KEY AUTO_INCREMENT,
	`USER_ID` INT NOT NULL,
	`TRANS_AMT` DECIMAL NOT NULL

);

CREATE TABLE `USER_TRANS_TOT_AMT` (
	`TRANS_TOT_AMT_ID` INT PRIMARY KEY AUTO_INCREMENT,
	`USER_ID` INT NOT NULL,
	`TOT_AMT` INT NOT NULL DEFAULT 0
);